table DimREIT
	lineageTag: auto-dimreit

	column stock_code
		dataType: string
		lineageTag: f7cb032a-8d62-45c1-8f63-5ff3bb110aaa
		summarizeBy: none
		sourceColumn: stock_code

		annotation SummarizationSetBy = Automatic

	column company_name
		dataType: string
		lineageTag: d845e8cd-1a45-45ab-a4ba-f42c77a84686
		summarizeBy: none
		sourceColumn: company_name

		annotation SummarizationSetBy = Automatic

	column dart_corp_code
		dataType: string
		lineageTag: bb12c31e-1b79-4549-9707-dd0b556fcb9f
		summarizeBy: none
		sourceColumn: dart_corp_code

		annotation SummarizationSetBy = Automatic

	column market_cap_rank
		dataType: int64
		formatString: 0
		lineageTag: 42dc5bc6-84be-44ad-9b74-e900f3075e28
		summarizeBy: none
		sourceColumn: market_cap_rank

		annotation SummarizationSetBy = Automatic

	column market_cap
		dataType: double
		formatString: #,0.0
		lineageTag: 5fcbd1f1-1539-4e7c-87a5-8bded5a1309c
		summarizeBy: sum
		sourceColumn: market_cap

		annotation SummarizationSetBy = Automatic

	column market
		dataType: string
		lineageTag: bc0f102a-2f80-4266-9335-c75f67a71543
		summarizeBy: none
		sourceColumn: market

		annotation SummarizationSetBy = Automatic

	column reit_type
		dataType: string
		lineageTag: 803af227-8952-4af8-9854-e361850ee9a3
		summarizeBy: none
		sourceColumn: reit_type

		annotation SummarizationSetBy = Automatic

	column main_asset_type
		dataType: string
		lineageTag: 5fb936e6-cd30-41e2-8acb-0c783350def3
		summarizeBy: none
		sourceColumn: main_asset_type

		annotation SummarizationSetBy = Automatic

	column main_region
		dataType: string
		lineageTag: af909c9f-1510-4335-91a7-04eef11f657d
		summarizeBy: none
		sourceColumn: main_region

		annotation SummarizationSetBy = Automatic

	column note
		dataType: string
		lineageTag: 9cc75f9d-1309-4690-b500-9ac7ab6a0c9d
		summarizeBy: none
		sourceColumn: note

		annotation SummarizationSetBy = Automatic

	partition DimREIT = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents(pExportFolder & "\dim_reit.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{"stock_code", type text}, {"company_name", type text}, {"dart_corp_code", type text}, {"market_cap_rank", Int64.Type}, {"market_cap", type number}, {"market", type text}, {"reit_type", type text}, {"main_asset_type", type text}, {"main_region", type text}, {"note", type text}}, "ko-KR")
				in
				  ChangedType

	annotation PBI_ResultType = Table
